var numbers = [1, 2, 3, 4, 5];
numbers.push(6);
console.log(numbers);
var lastNumber = numbers.pop();
console.log(lastNumber);
console.log(numbers);
var firstNumber = numbers.shift();
console.log(firstNumber);
console.log(numbers);
numbers.unshift(0);
console.log(numbers);
